# Setup
title:               Moodser Hussain
tagline:             'Research Scholar'
description:         'An experienced lecturer with a demonstrated history of working in the field of computer science. Skilled in Natural Language Processing (NLP), Data Science, and Machine Learning.'
url:                 moodser.github.io
baseurl:             'https://moodser.github.io/'
paginate:            5
#permalink:           pretty

# About/contact
author:
  name:              Moodser Hussain
  url:               moodser.github.io
  email:             moodser.hussain@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
